// Logo templates for quick styling
const logoTemplates = [
    {
        name: '科技蓝',
        brandName: 'TechCorp',
        slogan: '创新科技',
        icon: 'fas fa-microchip',
        textColor: '#2C3E50',
        iconColor: '#3498DB',
        bgColor: '#FFFFFF',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 48,
        fontWeight: '700',
        iconPosition: 'left',
        iconSize: 48,
        spacing: 16,
        padding: 40,
        borderRadius: 0
    },
    {
        name: '优雅紫',
        brandName: 'Elegance',
        slogan: '优雅生活',
        icon: 'fas fa-gem',
        textColor: '#FFFFFF',
        iconColor: '#E8DAEF',
        bgColor: '#6C5CE7',
        fontFamily: "'Playfair Display', serif",
        fontSize: 52,
        fontWeight: '700',
        iconPosition: 'left',
        iconSize: 44,
        spacing: 20,
        padding: 45,
        borderRadius: 12
    },
    {
        name: '自然绿',
        brandName: 'GreenLife',
        slogan: '绿色生活',
        icon: 'fas fa-leaf',
        textColor: '#27AE60',
        iconColor: '#27AE60',
        bgColor: '#FFFFFF',
        fontFamily: "'Open Sans', sans-serif",
        fontSize: 46,
        fontWeight: '600',
        iconPosition: 'top',
        iconSize: 56,
        spacing: 12,
        padding: 40,
        borderRadius: 8
    },
    {
        name: '商务黑',
        brandName: 'BUSINESS',
        slogan: 'Professional',
        icon: 'fas fa-briefcase',
        textColor: '#FFFFFF',
        iconColor: '#F1C40F',
        bgColor: '#2C3E50',
        fontFamily: "'Oswald', sans-serif",
        fontSize: 44,
        fontWeight: '500',
        iconPosition: 'left',
        iconSize: 40,
        spacing: 18,
        padding: 40,
        borderRadius: 0
    },
    {
        name: '活力橙',
        brandName: 'Spark',
        slogan: '点燃激情',
        icon: 'fas fa-bolt',
        textColor: '#E74C3C',
        iconColor: '#F39C12',
        bgColor: '#FFF5E6',
        fontFamily: "'Poppins', sans-serif",
        fontSize: 50,
        fontWeight: '700',
        iconPosition: 'left',
        iconSize: 52,
        spacing: 14,
        padding: 38,
        borderRadius: 20
    },
    {
        name: '极简白',
        brandName: 'minimal',
        slogan: '',
        icon: 'fas fa-circle',
        textColor: '#333333',
        iconColor: '#333333',
        bgColor: '#FFFFFF',
        fontFamily: "'Lato', sans-serif",
        fontSize: 42,
        fontWeight: '300',
        iconPosition: 'left',
        iconSize: 20,
        spacing: 12,
        padding: 50,
        borderRadius: 0
    },
    {
        name: '创意粉',
        brandName: 'Creative',
        slogan: 'Design Studio',
        icon: 'fas fa-palette',
        textColor: '#2D3436',
        iconColor: '#FD79A8',
        bgColor: '#FFEEF5',
        fontFamily: "'Poppins', sans-serif",
        fontSize: 48,
        fontWeight: '600',
        iconPosition: 'top',
        iconSize: 60,
        spacing: 16,
        padding: 45,
        borderRadius: 16
    },
    {
        name: '咖啡棕',
        brandName: 'CaféHouse',
        slogan: '品味生活',
        icon: 'fas fa-coffee',
        textColor: '#5D4037',
        iconColor: '#795548',
        bgColor: '#FFF8E1',
        fontFamily: "'Playfair Display', serif",
        fontSize: 44,
        fontWeight: '400',
        iconPosition: 'left',
        iconSize: 42,
        spacing: 14,
        padding: 40,
        borderRadius: 8
    },
    {
        name: '运动红',
        brandName: 'FITNESS',
        slogan: 'POWER UP',
        icon: 'fas fa-dumbbell',
        textColor: '#FFFFFF',
        iconColor: '#FFFFFF',
        bgColor: '#E74C3C',
        fontFamily: "'Oswald', sans-serif",
        fontSize: 46,
        fontWeight: '700',
        iconPosition: 'left',
        iconSize: 44,
        spacing: 16,
        padding: 40,
        borderRadius: 4
    },
    {
        name: '海洋蓝',
        brandName: 'OceanWave',
        slogan: '探索深蓝',
        icon: 'fas fa-water',
        textColor: '#FFFFFF',
        iconColor: '#74B9FF',
        bgColor: '#0984E3',
        fontFamily: "'Montserrat', sans-serif",
        fontSize: 44,
        fontWeight: '500',
        iconPosition: 'top',
        iconSize: 54,
        spacing: 12,
        padding: 45,
        borderRadius: 50
    },
    {
        name: '金融金',
        brandName: 'GOLDBANK',
        slogan: '财富增值',
        icon: 'fas fa-coins',
        textColor: '#B8860B',
        iconColor: '#DAA520',
        bgColor: '#FFFEF0',
        fontFamily: "'Roboto', sans-serif",
        fontSize: 42,
        fontWeight: '700',
        iconPosition: 'left',
        iconSize: 40,
        spacing: 16,
        padding: 40,
        borderRadius: 0
    },
    {
        name: '夜空紫',
        brandName: 'StarNight',
        slogan: '仰望星空',
        icon: 'fas fa-star',
        textColor: '#DDA0DD',
        iconColor: '#FFD700',
        bgColor: '#1A1A2E',
        fontFamily: "'Poppins', sans-serif",
        fontSize: 48,
        fontWeight: '600',
        iconPosition: 'right',
        iconSize: 36,
        spacing: 14,
        padding: 42,
        borderRadius: 10
    }
];

// Export for use in other modules
window.logoTemplates = logoTemplates;
